name: activitypub
description: A library for the ActivityPub standard. Created an also used by Fedodo.
version: 1.1.0
repository: https://github.com/Fedodo/Fedodo.Pub.ActivityPub

environment:
  sdk: ^3.0.2

dependencies:
  jwt_decoder: ^2.0.1
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
