name: PrepareForPublish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if current version is incorrect
        run: |

          version=$(grep 'version:' pubspec.yaml | tail -n1 | awk '{ print $2}')

          echo $version

          echo "PUBSPEC_VERSION=version" >> "$GITHUB_ENV"

          echo "${{ env.PUBSPEC_VERSION }}"

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GH_TOKEN }}"
      #     automatic_release_tag: "${{ env.VERSION }}"
      #     prerelease: false

