name: PrepareForPublish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set PUBSPEC_VERSION
        run: |
          version=$(grep 'version:' pubspec.yaml | tail -n1 | awk '{ print $2}')

          echo $version

          echo "PUBSPEC_VERSION=$version" >> "$GITHUB_ENV"

      - run: echo "${{ env.PUBSPEC_VERSION }}"

      - name: Check for Tag
        run: |
          TAG="v${{ env.PUBSPEC_VERSION }}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} exists"
            exit 1
          else
            echo "Tag ${TAG} does not exist"
          fi

      - run: sed -i '1s/^/## ${{ env.PUBSPEC_VERSION }}\n\n /' CHANGELOG.md

      - name: Commit changelog
        uses: test-room-7/action-update-file@v1
        with:
            file-path: CHANGELOG.md
            commit-msg: 📝 Updated Changelog
            github-token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GH_TOKEN }}"
      #     automatic_release_tag: "${{ env.PUBSPEC_VERSION }}"
      #     prerelease: false
