name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git pull origin main

      # Setup Dart SDK with JWT token
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f

      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: dart pub get
        # working-directory: ${{ inputs.working-directory }}

      - name: Publish - dry run
        run: dart pub publish --dry-run
        # working-directory: ${{ inputs.working-directory }}

      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
        # working-directory: ${{ inputs.working-directory }}
